import "dotenv/config";
import bcrypt from "bcryptjs";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../src/generated/prisma/client";
const connectionString=process.env.DATABASE_URL;if(!connectionString)throw new Error("DATABASE_URL is required");
const db=new PrismaClient({adapter:new PrismaPg({connectionString})});
const categories=["India","Politics","Business","World","Technology","Sports","Culture"]; const tags=["Breaking","Analysis","Economy","Growth","Media","Cities","Society","Finance"];
async function main(){const email=(process.env.ADMIN_EMAIL||"admin@shambhunews.com").toLowerCase();const password=process.env.ADMIN_PASSWORD||"change-me-now";const hash=await bcrypt.hash(password,12);const user=await db.user.upsert({where:{email},update:{name:"Editorial Desk",passwordHash:hash,role:"ADMIN"},create:{name:"Editorial Desk",email,passwordHash:hash,role:"ADMIN"}});for(const name of categories)await db.category.upsert({where:{name},update:{},create:{name,slug:name.toLowerCase()}});for(const name of tags)await db.tag.upsert({where:{name},update:{},create:{name,slug:name.toLowerCase()}});await db.siteSetting.upsert({where:{id:"main"},update:{},create:{id:"main",siteName:"Shambunews",tagline:"News that matters. Stories that stay."}});const india=await db.category.findUniqueOrThrow({where:{name:"India"}});const growth=await db.tag.findUniqueOrThrow({where:{name:"Growth"}});const analysis=await db.tag.findUniqueOrThrow({where:{name:"Analysis"}});const exists=await db.article.findUnique({where:{slug:"indias-next-growth-chapter"}});if(!exists)await db.article.create({data:{title:"India’s next growth chapter is being written beyond the metros",slug:"indias-next-growth-chapter",excerpt:"A new wave of infrastructure, digital services and smaller-city entrepreneurship is reshaping the country’s economic map.",content:"The next growth story is no longer confined to the biggest metros. Smaller cities are becoming places where new businesses launch, talent stays, and digital services reach new customers.\n\n## What is changing\n\nBetter connectivity, more accessible digital tools and a broader services economy are lowering the barriers to starting and scaling a business.\n\n> The map of opportunity is getting wider.\n\nFor publishers, that shift also means the most useful local stories are becoming increasingly relevant to national audiences.",featuredImage:"https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=1400&q=80",imageAlt:"India city skyline",status:"PUBLISHED",featured:true,publishedAt:new Date(),authorId:user.id,categories:{create:{categoryId:india.id}},tags:{create:[{tagId:growth.id},{tagId:analysis.id}]}}});console.log(`Seeded admin ${email}`)}
main().finally(()=>db.$disconnect());
